# Generated by Django 4.2 on 2023-12-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
                ('type', models.CharField(max_length=10)),
                ('coordinates', models.JSONField()),
                ('thumbnail', models.TextField()),
                ('session_id', models.UUIDField()),
            ],
        ),
    ]
